config/routes.rb
JobBoard::Application.routes.draw do
  root :to => "jobs#index"
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :access_key, :category_id, :description, :email, :is_active, :is_featured, :location, :logo, :name, :title, :url
  validates :access_key, :email, :category_id, :description, :is_featured, :location, :name, :title, :url, presence: true
  #mount_uploader :logo, PictureUploader
  #validates :access_key, presence: true, uniqueness: true
  #validates :email, confirmation: true
  #validates :email_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  	@jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new 
  end

  def create
    @job = Job.new(params[:job])
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/create.html.erb
<h1>Job was created</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/destroy.html.erb
<h1>Jobs was deleted</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Edit Job Post</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/index.html.erb
<table class="table table-striped">
<caption>Current Job Openings</caption>
  <thead>
    <tr>
      <th>Job Title</th>
      <th>Location</th>
      <th>Company Name</th>
      <th>Date Posted</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= link_to job.title, job_path(job) %></td>
      <td><%= job.location %></td>
      <td><%= job.name %></td>
      <td><%= job.created_at.strftime("%b %d") %></td>
      <td><%= link_to "Edit", edit_job_path(job) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h2>Post a New Job</h2>
<%= form_for @job do |job| %>
  <%= job.label :title, "Job Title"%> <%= job.text_field :title %>
  <%= job.label :category_id %> <%= job.text_field :category_id %>
  <%= job.label :location %> <%= job.text_field :location %>
  <%= job.label :description, "Job Description" %> <%= job.text_area :description %>
  <%= job.label :name %> <%= job.text_field :name %>
  <%= job.label :logo %> <%= job.file_field :logo %>
  <%= job.label :url, "Website" %> <%= job.text_field :url %>
  <%= job.label :email, "Email Address" %> <%= job.text_field :email %>
  <%= job.hidden_field :is_active, :value => true %>
  <%= job.hidden_field :is_featured, :value => true %>
  <%= job.hidden_field :access_key, :value => SecureRandom.urlsafe_base64(8, false) %>
  <p><%= job.submit "Post Job" %></p>
<% end %>
<p><%= link_to "Back to Index", jobs_path %></p>

<script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js">
</script>

<script type="text/javascript">
//<![CDATA[
var job_description;
job_description = new nicEditor({fullPanel : true}).panelInstance('job_description');
//]]>
</script>

app/views/jobs/show.html.erb
<p><%= link_to "<< Back to Jobs", jobs_path %></p>
<h1><%= @job.title %></h1>
<%= @job.created_at.strftime("%b %d") %>
<h4><%= @job.category_id %> by <%= @job.location %></h4>
<p><%= @job.description %></p>
<address>
  <h2><%= @job.name %></h2>
  <%= link_to @job.url %><br>
  <%= mail_to @job.email %>
</address>

app/views/jobs/update.html.erb
<h1>Job Update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Job Board</a>
      <ul class="nav">
        <li><%= link_to "All Jobs", jobs_path %></li>
        <li><%= link_to "Post New Job", new_job_path %></li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
<%= yield %>
</div>

<footer>
  <div class="container">
    &copy; <%= Time.now.year %> Job Board
  </div>
</footer>
</body>
</html>